### ISSUE TITLE
[openshift] secure service traffic using service serving certificate secrets

### ISSUE THREAD

**Issue by lburgazzoli** [KaotoIO/kaoto-operator#105]
As today, the communication between the ingress and the kaoto backend is not encrypted. 
On OpenShift we must use service-serving-certificate to re-encrypt the traffic between the router and the backend, see:

- https://docs.openshift.com/container-platform/4.13/security/certificates/service-serving-certificate.html
- https://docs.openshift.com/container-platform/4.13/networking/routes/secured-routes.html#nw-ingress-creating-a-reencrypt-route-with-a-custom-certificate_secured-routes

**Comment by lhein** [comment]
Closing as no longer relevant
