### ISSUE TITLE
Install Kaoto README has missing file and typo

### ISSUE THREAD

**Issue by victorchapman** [KaotoIO/kaoto-operator#118]
<img width="806" alt="Screenshot 2023-09-05 at 2 51 58 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/a54e88ff-0a0a-4e15-b5ac-907edc5045ea">

https://raw.githubusercontent.com/KaotoIO/kaoto-operator/main/kubernetes/kaoto.yaml - File does not exist

kubect should be kubectl

**Comment by lordrip** [comment]
Thanks for reporting this @victorchapman , we'll take a look :)
