### ISSUE TITLE
Ingress problem with /designer. Found within kaoto-operator pod logs MAJOR

### ISSUE THREAD

**Issue by victorchapman** [KaotoIO/kaoto-operator#122]
<img width="1865" alt="Screenshot 2023-09-08 at 2 47 18 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/bf2f530f-a442-4bf9-9e10-b211f0f40c9f">
<img width="618" alt="Screenshot 2023-09-08 at 2 48 28 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/aa58b88d-0b1f-47d7-867c-fbe6693b8c1d">

Here is a similar issue:
https://github.com/argoproj/argo-cd/issues/9025

Here is a potential solution: 
<img width="869" alt="Screenshot 2023-09-08 at 2 51 47 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/1117a52b-306c-4f9b-92dc-e2afac25f487">
<img width="794" alt="Screenshot 2023-09-08 at 2 52 55 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/0e31f88a-2b98-4891-8a5c-5f4d2df9826f">

When I got to 
<img width="201" alt="Screenshot 2023-09-08 at 2 56 08 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/dee4dfca-b475-4eb9-a53d-86071dabc2e9">

I get this
<img width="873" alt="Screenshot 2023-09-08 at 2 54 49 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/ed2f06e1-ba33-4d26-9e92-84342c13af9b">

I'm using minikube on a M1 Macbook Pro. Let me know if you need more config info

**Comment by lburgazzoli** [comment]
what ingress did you set up ?

**Comment by victorchapman** [comment]
I ran minikube start addons ingress

**Comment by victorchapman** [comment]
Do you have to run minikube tunnel for it to work?

**Comment by lburgazzoli** [comment]
I guess 

    minikube start --addons ingress

I have not experienced this issue to be honest but never tried on mac. 
Can you provide all the steps ?

**Comment by victorchapman** [comment]
<img width="828" alt="Screenshot 2023-09-08 at 3 07 52 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/1ba9eca8-eac4-4d59-bb18-a1a206e93983">
I'm just waiting, hopefully the service starts, if this doesn't work ill send the you steps

**Comment by victorchapman** [comment]
Hi @lburgazzoli, it is still not working even when the service designer is running.
I want to confirm that it is running correctly, when I type the correct password the terminal freezes like this 
<img width="923" alt="Screenshot 2023-09-08 at 3 37 02 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/a97bc85f-eec8-49fa-b480-ba5f8135f2f6">
I believe its running because when I quit using command C it says this 
<img width="354" alt="Screenshot 2023-09-08 at 3 37 35 PM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/485dffe0-dac0-4898-aa54-2b7d281c0375">
I'm still getting the original error up above in my kaoto-operator pod, ill provide all the steps if you can confirm that my minikube tunnel is working properly.

**Comment by victorchapman** [comment]
@lburgazzoli here are the steps:
1. minikube start --addons ingress
2. kubectl create -f “https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.25.0/crds.yaml
3. kubectl create -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.25.0/olm.yaml
4. I create file called registry-setup.yaml
<img width="713" alt="Screenshot 2023-09-11 at 9 40 59 AM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/0365417e-9c30-41cc-838b-35b58757aba1">
5. kubectl apply -f {path_of_registry-setup.yaml}
6. kamel install —registry {registry_cluster-ip} —force
7. I then follow the instructions on installing Kaoto with minikube

I have the ability to run kamel integrations with kamel run, I'm not sure if my ingress is messed up or something is wrong with the kaoto-operator. I'm still getting this error.
<img width="1727" alt="Screenshot 2023-09-11 at 9 44 02 AM" src="https://github.com/KaotoIO/kaoto-operator/assets/65624008/89eac463-d42a-4099-a809-288a6c35326e">

**Comment by lburgazzoli** [comment]
@victorchapman can you try to run the operator locally and see if the problem persist ? I don't have a mac to test it
