### ISSUE TITLE
Kaoto instance not working when installed in OpenShift Local (former CRC)

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-operator#212]
I installed the Kaoto operator 0.0.12 on my local OpenShift Local instance. After that I created a new demo instance for Kaoto using the following YAML file: https://github.com/KaotoIO/kaoto-operator/blob/main/config/samples/designer_test.yaml

This set up the instance and the route to access the instance:
![grafik](https://github.com/KaotoIO/kaoto-operator/assets/435853/6fc5b216-6192-42f0-a1dc-f7eef9d4f575)

When clicking the link I was forwarded to the following screen:
![grafik](https://github.com/KaotoIO/kaoto-operator/assets/435853/b1185ad2-b10c-49f9-ab40-2710d36f7475)

**Comment by oscerd** [comment]
This seems to be a problem only on CRC, on a real Openshift it works fine.

**Comment by lhein** [comment]
It must be something on my machine as Paul tried it with his local instance and it worked fine.

**Comment by lordrip** [comment]
Do we have instructions about how to install it?
