### ISSUE TITLE
Add `kaoto-bot` to the `ci.yaml` file in the community-operators repository

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-operator#213]
It would be beneficial to add `kaoto-bot` to the `ci.yaml` so its PRs are approved in an automated fashion.

![image](https://github.com/KaotoIO/kaoto-operator/assets/16512618/a6f53d36-f41f-41d9-94f1-5e9037ba5b33)

**Comment by oscerd** [comment]
Any other to add?

**Comment by lordrip** [comment]
I think for the time being, this is the only bot we have 😃

**Comment by oscerd** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4428
https://github.com/k8s-operatorhub/community-operators/pull/4245

**Comment by oscerd** [comment]
Done.
