### ISSUE TITLE
Use images defined in kaoto CRD 

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-operator#5]
This will help easily rotate custom images of kaoto for development purposes.

**Comment by kahboom** [comment]
hey @mmelko this is still in Sprint 5, should I move it to Sprint 6 or was it done?

**Comment by kahboom** [comment]
@mmelko I'm back again, two months later 😂  should this still be open?

**Comment by lburgazzoli** [comment]
done
