### ISSUE TITLE
Minikube Deployment

### ISSUE THREAD

**Issue by zetfactor** [KaotoIO/kaoto-operator#69]
I need some advise on how to succesfully deploy a fully working 

1-Installed Minikube.
2- Installed Kamel-cli (not sure if this required or no)
3-Deployed Kaoto UI and Kaoto Backend (using latest Docker images)
4-followed instructions here: https://kaoto.io/docs/user-guide/
5-When I click deploy nothing happens in the cluster, however when I view the logs :

`WARN  [io.kao.bac.api.ser.dep.gen.cam.IntegrationDeploymentGeneratorService] (executor-thread-3) Error extracting the list of integrations.: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/camel.apache.org/v1/namespaces/kaoto-demo/integrations. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. integrations.camel.apache.org is forbidden: User "system:serviceaccount:kaoto:default" cannot list resource "integrations" in API group "camel.apache.org" in the namespace "kaoto-demo".
`

6- Though I should install the operator: I cloned the Main branch , and followed all steps. until **Make Deploy**, then I get the following error.

> home/mz/Desktop/Kaoto/kaoto-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
bash: line 1: /home/user/Desktop/Kaoto/kaoto-operator/bin/controller-gen: No such file or directory
make: *** [Makefile:89: manifests] Error 127

Not sure what I am doing wrong. It would be great if someone support with the correct way to install a functional Kaoto deployment.

Thanks

**Comment by victorchapman** [comment]
I got to this point and figured out a way to fix it 
You have to run this command after deleting the clusterolebinding that is generated. Just go into the dashboard and find the clusterolebinding tab and delete the kaoto-operator role and then recreate it with this command.
kubectl create clusterrolebinding kaoto-operator --clusterrole=cluster-admin --serviceaccount=kaoto-system:kaoto-operator

After getting passed this another error shows up which is my recent issue on this repo.

**Comment by lburgazzoli** [comment]
closed as not more relevant
