### ISSUE TITLE
Release to OperatorHUB and RedHat Marketplace automation

### ISSUE THREAD

**Issue by lburgazzoli** [KaotoIO/kaoto-operator#98]
It would be nice to have a GitHub Workflow that streamline the process to publish the Kaoto Operator to [Openshift Community Operators](https://github.com/redhat-openshift-ecosystem/community-operators-prod) and [Kubernetes Community Operators](https://github.com/k8s-operatorhub/community-operators)

Ideally the action should take two parameters:
1. bundle version
2. operator version
3. replaceVersion

Then it should:
1. checkout the kaoto operator that matches the `operator version` input value
2. generate the bundle files
3. amend the bundle files to be compatible with the requirements of the community operator repos
4. automatically open a PR to the mentioned repos

**Comment by oscerd** [comment]
With #176 we are able to automatic tag and release the operator, and attach the bundle to the release. The next step will be to download the bundle and modify it to prepare for opening the PR

**Comment by oscerd** [comment]
We are now able to prepare all the required branches to release the operator. We need to automatically open the PRs now.
